
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  profiles:
    active: masterslave


sharding:
  jdbc:
    config:
      sharding:
        props:
          sql:
            show: true # 显示sql