sharding:
  jdbc:
    datasource:
      names: ds_master,ds_slave_0
      ds_master:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.134.128:3306/master-slave
        username: root
        password: 123456
      ds_slave_0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.134.128:3316/master-slave
        username: slave_reader
        password: 123456
    config:
      masterslave: # 这里主从用了这个配置，如果是分片‘sharding.jdbc.config.sharding’
        name: ds_ms
        # 主库数据源名称
        master-data-source-name: ds_master
        # 从库数据源名称列表
        slave-data-source-names: ds_slave_0
        #从库负载均衡算法类名称。该类需实现MasterSlaveLoadBalanceAlgorithm接口且提供无参数构造器
        #load-balance-algorithm-class-name:
        #从库负载均衡算法类型，可选ROUND_ROBIN,RANDOM,如果load-balance-algorithm-class-name存在，这个将被忽略
        load-balance-algorithm-type: ROUND_ROBIN





